name: flutter_device_locale
description: A Flutter plugin for retrieving the device locale information.
version: 1.0.0
homepage: https://leadcode.dev
repository: https://github.com/bratan/flutter_device_locale

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.leadcode.flutter_device_locale
        pluginClass: FlutterDeviceLocalePlugin
      ios:
        pluginClass: FlutterDeviceLocalePlugin
      web:
        pluginClass: FlutterDeviceLocaleWebPlugin
        fileName: src/web.dart
      linux:
        pluginClass: FlutterDeviceLocalePlugin
